apiVersion: v1
kind: Namespace
metadata:
  name: ns-api-kobocollect-dev
  labels:
    env: dev
    group: lot-1
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: ns-api-kobocollect-dev
  labels:
    env: dev
    group: lot-1
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaXRsYWIuaG9sb2dyYW0uY2Q6NTA1MCI6eyJ1c2VybmFtZSI6Imhhcm9sZCIsInBhc3N3b3JkIjoiNDhfNXpldUJtWnk3UlNIRmZXUC0iLCJhdXRoIjoiYUdGeWIyeGtPalE0WHpWNlpYVkNiVnA1TjFKVFNFWm1WMUF0In19fQ==

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-api-kobocollect
  namespace: ns-api-kobocollect-dev
  labels:
    env: dev
    group: lot-1
data:
  MSSQL_DB: eRecensement
  MSSQL_USER: sa
  MSSQL_PASSWORD: hids++--@@987654321#]*
  MSSQL_SERVER: mssql+pyodbc://gesRecens:hids+1234@195.26.250.58@195.26.250.58/eRecensement?driver=FreeTDS&port=1433&odbc_options='TDS_Version=8.0
  TZ: Africa/Kinshasa

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-kobocollect
  namespace: ns-api-kobocollect-dev
  labels:
    env: dev
    group: lot-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-kobocollect
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api-kobocollect
        env: dev
        group: lot-1
    spec:
      containers:
        - name: api-kobocollect
          image: gitlab.hologram.cd:5050/backend-erecettes-dgrk/kobocollect-api:dev
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: config-api-kobocollect
          resources:
            limits:
              memory: 1200Mi
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 200
            timeoutSeconds: 3
            periodSeconds: 30
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: api-kobocollect-service
  namespace: ns-api-kobocollect-dev
  labels:
    env: dev
    group: lot-1
spec:
  selector:
    app: api-kobocollect
  ports:
    - port: 9083
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-api-kobocollect
  namespace: ns-api-kobocollect-dev
  labels:
    env: dev
    group: lot-1
spec:
  ingressClassName: nginx
  rules:
    - host: 'api-kobocollect.apps.kubedev.hologram.cd'
      http:
        paths:
          - pathType: Prefix
            path: '/'
            backend:
              service:
                name: api-kobocollect-service
                port:
                  number: 9083
