apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-kobocollect.yml 

configMapGenerator:
  - name: config-api-kobocollect
    files:
        - config/dev/.env  # Chemin vers votre fichier d'environnement ou autre configuration n√©cessaire
    namespace: ns-api-kobocollect-dev  #
